### ISSUE TITLE
Using SapMachine in Cloud Foundry Apt Buildpack

### ISSUE THREAD

**Issue by gregorwolf** [SAP/SapMachine#777]
Hello SAP Machine Team,

I try to use SapMachine in the [Cloud Foundry Apt Buildpack](https://github.com/cloudfoundry/apt-buildpack). Additional dependencies can be specified via an apt.yaml file. I've used the [Installation documentation for Linux](https://github.com/SAP/SapMachine/wiki/Installation#-linux) as my reference and created:

```yaml
---
keys:
- https://dist.sapmachine.io/debian/sapmachine.old.key
- https://dist.sapmachine.io/debian/sapmachine.key
repos:
- deb http://dist.sapmachine.io/debian/amd64/ stable main
packages:
- sapmachine-11-jdk
```

but unfortunately the build of my module failed with the following error message:

```
E: The repository 'http://dist.sapmachine.io/debian/amd64/ stable Release' does not have a Release file.
```

I've also tried http://dist.sapmachine.io/debian/ and http://dist.sapmachine.io/. But always with the simmilar result. Looking forward for a tip how to specify the SapMachine repository. 

The project where I want to use it is available at [pg-beershop](https://github.com/gregorwolf/pg-beershop/). It shows how to use the cds-pg and cds-dbm modules to deploy a [SAP Cloud Application Programming Model](https://cap.cloud.sap/docs/) application to SAP Cloud Platform - Cloud Foundry.

Best regards
Gregor
